"""Added DB Schema Functionality Fix

Revision ID: 90afbd79f5c9
Revises: 6923b1f9a1d4
Create Date: 2025-06-29 17:42:48.675124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90afbd79f5c9'
down_revision = '6923b1f9a1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_roles_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_roles_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_roles_role_id'))

    # ### end Alembic commands ###
