"""Added metadata

Revision ID: c88e84db49e1
Revises: e3f139417643
Create Date: 2025-08-16 15:16:19.733737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88e84db49e1'
down_revision = 'e3f139417643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_metadata', sa.JSON(), nullable=True))
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False,
               postgresql_using="content::json")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False,
               postgresql_using="content::json")
        batch_op.drop_column('ai_metadata')

    # ### end Alembic commands ###
